module.exports = [{
    name: "Skitarii Vanguard",
    movement: '6"',
    weaponSkill: "4+",
    ballisticSkill: "3+",
    strength: "3",
    toughness: "3",
    wounds: "1",
    attack: "1",
    leadership: "6",
    saveCharacteristic: "4+",
    abilities: "Rad-Saturation: While an enemy unit is within 1 inch of a unit with this ability, reduce their toughness by 1",
    unitImage: "https://th.bing.com/th/id/OIP.sgDYOg8cQIzbLdleqS0sTAHaJ4?w=160&h=213&c=7&r=0&o=5&pid=1.7",

    weaponName: "Radium Carbine",
    range: '18"',
    type: "assault 3",
    weaponStrength: "3",
    ap: "0",
    damage: "1",
    weaponAbilites: "Auto wounds on hit roles of 6",
    weaponImage: "https://th.bing.com/th/id/OIP.-W69ca7miaSNsGcLni0mQAAAAA?w=220&h=106&c=7&r=0&o=5&pid=1.7"
},
{
    name: "Skitarii Ranger",
    movement: '6"',
    weaponSkill: "4+",
    ballisticSkill: "3+",
    strength: "3",
    toughness: "3",
    wounds: "1",
    attack: "1",
    leadership: "6",
    saveCharacteristic: "4+",
    abilities: "None",
    unitImage: "https://th.bing.com/th/id/OIP.QkcNl-N2qbRE_RGmIPptxwHaFj?w=219&h=180&c=7&r=0&o=5&pid=1.7",

    weaponName: "Galvanic Rifle",
    range: '30"',
    type: "Heavy 2",
    weaponStrength: "4",
    ap: "-1",
    damage: "1",
    weaponAbilites: "None",
    weaponImage: "https://th.bing.com/th/id/OIP.bLfDgsFKPMd4J2dtqOhS1QAAAA?w=165&h=190&c=7&r=0&o=5&pid=1.7"
},
{
    name: "Solitaire",
    movement: '12"',
    weaponSkill: "2+",
    ballisticSkill: "2+",
    strength: "3",
    toughness: "3",
    wounds: "5",
    attack: "8",
    leadership: "9",
    saveCharacteristic: "6+",
    abilities: "Impossible Form: 3+ invulnerable save",
    unitImage: "https://th.bing.com/th/id/R.0b50b2307e5b0cba868e01913db9050c?rik=8X0pPPzgUNKZnw&riu=http%3a%2f%2f3.bp.blogspot.com%2f-1X8n62FwLEY%2fVQksxxHWaEI%2fAAAAAAAAAyo%2fPYbuE18PfeQ%2fs1600%2fMale_Troupe_Master.png&ehk=0PnGwOZo0lMRg79bdii%2fvCpwMO2FLcF9n6%2bkCP8jLUE%3d&risl=&pid=ImgRaw&r=0",

    weaponName: "Harlequins Caress",
    range: 'Melee',
    type: "Melee",
    weaponStrength: "+2",
    ap: "-2",
    damage: "1",
    weaponAbilites: "None",
    weaponImage: "https://th.bing.com/th/id/OIP.c8gvxHgxLyHhWNt8__GqAAHaF7?w=253&h=187&c=7&r=0&o=5&pid=1.7"
},
{
    name: "Death Jester",
    movement: '8"',
    weaponSkill: "2+",
    ballisticSkill: "2+",
    strength: "3",
    toughness: "3",
    wounds: "5",
    attack: "4",
    leadership: "9",
    saveCharacteristic: "6+",
    abilities: "Halo-suit: 4+ invulnerable save",
    unitImage: "https://th.bing.com/th/id/OIP.n66dsDsN9iyzVjnbNtWU-gHaKE?w=186&h=253&c=7&r=0&o=5&pid=1.7",

    weaponName: "Shrieker Cannon(Shrieker)",
    range: '24"',
    type: "Assault 1",
    weaponStrength: "6",
    ap: "-1",
    damage: "1",
    weaponAbilites: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -3. Each time an INFANTRY model is slain by an attack made with this weapon, its unit suffers D3 mortal wounds. If any models in a unit are slain by this weapon, subtract 2 from that unit's Leadership characteristic until the end of the turn.",
    weaponImage: "https://th.bing.com/th/id/OIP.JsGKaJeNKQKTP4dHAmVL3gAAAA?w=242&h=87&c=7&r=0&o=5&pid=1.7"
}, {
    name: "Sicarian Ruststalker",
    movement: '8"',
    weaponSkill: "3+",
    ballisticSkill: "3+",
    strength: "4",
    toughness: "3",
    wounds: "2",
    attack: "3",
    leadership: "6",
    saveCharacteristic: "4+",
    abilities: "Enhanced Bionics: 5+ invulnerable save | Optimised Gait: This unit can ignore any or all modifiers to its Move characteristic, with the exception of that incurred due to the Deprecation effect of the Bulwark Imperative. This unit can ignore any or all modifiers to its Advance rolls and charge rolls | Wasteland Stalkers: Each time a ranged attack is allocated to a model in this unit while it is receiving the benefits of cover, add an additional 1 to any armour saving throw made against that attack",
    unitImage: "https://vignette.wikia.nocookie.net/warhammer40k/images/3/3c/Sicarian_Rustwalkers.png/revision/latest?cb=20160218000732",

    weaponName: "Transonic Blades",
    range: 'Melee',
    type: "Melee",
    weaponStrength: "+1",
    ap: "-3",
    damage: "1",
    weaponAbilites: "Each time an attack is made with this weapon, an unmodified wound roll of 6 inflicts 1 mortal wound on the target in addition to any normal damage.",
    weaponImage: "https://vignette.wikia.nocookie.net/warhammer40k/images/6/6a/Transonic_Blade.png/revision/latest?cb=20160303162403"
}
]